In [1]:
!conda list flexpart

# packages in environment at /home/patj/miniconda3/envs/softioli:
#
# Name                    Version                   Build  Channel
flexpart-output           0.1                       dev_0    <develop>
flexpart-sim              0.1                       dev_0    <develop>


In [2]:
!conda list common

# packages in environment at /home/patj/miniconda3/envs/softioli:
#
# Name                    Version                   Build  Channel
aws-c-common              0.4.57               he6710b0_1  
common                    0.1                       dev_0    <develop>
libbrotlicommon           1.0.9                h5eee18b_7  
libxkbcommon              1.0.1                h5eee18b_1  


In [3]:
!conda list xarray-extras

# packages in environment at /home/patj/miniconda3/envs/softioli:
#
# Name                    Version                   Build  Channel
xarray-extras             0.1                       dev_0    <develop>


In [4]:
!conda list h5

# packages in environment at /home/patj/miniconda3/envs/softioli:
#
# Name                    Version                   Build  Channel
h5netcdf                  1.2.0              pyhd8ed1ab_0    conda-forge
h5py                      3.7.0           py310he06866b_0  


In [5]:
!conda list hdf5

# packages in environment at /home/patj/miniconda3/envs/softioli:
#
# Name                    Version                   Build  Channel
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge


In [6]:
!conda list netcdf

# packages in environment at /home/patj/miniconda3/envs/softioli:
#
# Name                    Version                   Build  Channel
h5netcdf                  1.2.0              pyhd8ed1ab_0    conda-forge
libnetcdf                 4.8.1           nompi_hcd642e3_100    conda-forge
netcdf4                   1.6.2           py310h6d89c78_0  


In [7]:
import fpsim
fpsim

<module 'fpsim' from '/home/patj/SOFT-IO-LI/src/libs/fpsim/fpsim/__init__.py'>

---

### Bidouilles quand pbms avec h5necdf et tout

In [8]:
import xarray as xr
from pathlib import Path

In [9]:
path = Path('/o3p/patj/SOFT-IO-LI/flexpart10.4/flexpart_v10.4_3d7eebf/src/exercises/soft-io-li/flight_2018_001_1h_05deg/10j_100k_output/grid_time_20180603150000.nc')
path

PosixPath('/o3p/patj/SOFT-IO-LI/flexpart10.4/flexpart_v10.4_3d7eebf/src/exercises/soft-io-li/flight_2018_001_1h_05deg/10j_100k_output/grid_time_20180603150000.nc')

In [10]:
ds = xr.open_dataset(path)
ds 
# OK sans soucis avec test-softioli-light-env SANS h5netcdf
# OK sans soucis avec softioli-pbm-netcdf-h5netcdf AVEC h5netcdf et netcdf4 installés

<xarray.Dataset>
Dimensions:     (time: 240, longitude: 720, latitude: 360, height: 27,
                 numpoint: 2, numspec: 1, nageclass: 1, pointspec: 2)
Coordinates:
  * time        (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:0...
  * longitude   (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude    (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height      (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: numpoint, numspec, nageclass, pointspec
Data variables: (12/15)
    RELCOM      (numpoint) |S45 ...
    RELLNG1     (numpoint) float32 ...
    RELLNG2     (numpoint) float32 ...
    RELLAT1     (numpoint) float32 ...
    RELLAT2     (numpoint) float32 ...
    RELZZ1      (numpoint) float32 ...
    ...          ...
    RELEND      (numpoint) timedelta64[ns] ...
    RELPART     (numpoint) int32 ...
    RELXMASS    (numspec, numpoint) float32 ...
    LAGE        (nageclass) timedelta64[ns] ...
    ORO         (latitude, longitude) int32 ...
    spec001_mr  (nageclass, pointspec, time, height, latitude, longitude) float32 ...
Attributes: (12/37)
    Conventions:            CF-1.6
    title:                  FLEXPART model output
    institution:            NILU
    source:                 Version 10.4 (2019-11-12) model output
    history:                2021-08-04 11:20 +0200  created by macc on n202
    references:             Stohl et al., Atmos. Chem. Phys., 2005, doi:10.51...
    ...                     ...
    ind_source:             2
    ind_receptor:           2
    mquasilag:              0
    nested_output:          0
    surf_only:              0
    linit_cond:             0

In [11]:
ds = xr.open_dataset(path, engine='h5netcdf')
ds # OK sans soucis avec softioli-pbm-netcdf-h5netcdf AVEC h5netcdf et netcdf4 installés

<xarray.Dataset>
Dimensions:     (time: 240, longitude: 720, latitude: 360, height: 27,
                 numpoint: 2, numspec: 1, nageclass: 1, pointspec: 2)
Coordinates:
  * time        (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:0...
  * longitude   (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude    (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height      (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: numpoint, numspec, nageclass, pointspec
Data variables: (12/15)
    RELCOM      (numpoint) |S45 ...
    RELLNG1     (numpoint) float32 ...
    RELLNG2     (numpoint) float32 ...
    RELLAT1     (numpoint) float32 ...
    RELLAT2     (numpoint) float32 ...
    RELZZ1      (numpoint) float32 ...
    ...          ...
    RELEND      (numpoint) timedelta64[ns] ...
    RELPART     (numpoint) int32 ...
    RELXMASS    (numspec, numpoint) float32 ...
    LAGE        (nageclass) timedelta64[ns] ...
    ORO         (latitude, longitude) int32 ...
    spec001_mr  (nageclass, pointspec, time, height, latitude, longitude) float32 ...
Attributes: (12/37)
    Conventions:            CF-1.6
    title:                  FLEXPART model output
    institution:            NILU
    source:                 Version 10.4 (2019-11-12) model output
    history:                2021-08-04 11:20 +0200  created by macc on n202
    references:             Stohl et al., Atmos. Chem. Phys., 2005, doi:10.51...
    ...                     ...
    ind_source:             2
    ind_receptor:           2
    mquasilag:              0
    nested_output:          0
    surf_only:              0
    linit_cond:             0

In [12]:
import fpout
import xarray_extras as xrx

In [13]:
fpout.open_fp_dataset?

Signature:
fpout.open_fp_dataset(
    url,
    assign_releases_position_coords=True,
    pixel_area=False,
    chunks='auto',
    max_chunk_size=None,
)
Docstring: <no docstring>
File:      ~/SOFT-IO-LI/src/libs/fpout/fpout/grid_time.py
Type:      function

In [14]:
ds_test_fpout = fpout.open_fp_dataset(path, max_chunk_size=1e8)
ds_test_fpout

/home/patj/SOFT-IO-LI/src/libs/fpout/fpout/grid_time.py:176: FutureWarning: use open_dataset
  warnings.warn('use open_dataset', FutureWarning)


<xarray.Dataset>
Dimensions:           (time: 240, longitude: 720, latitude: 360, height: 27,
                       numpoint: 2, numspec: 1, nageclass: 1, release_time: 2)
Coordinates:
  * time              (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-2...
  * longitude         (longitude) float32 -179.2 -178.8 -178.2 ... 179.8 180.2
  * latitude          (latitude) float32 -89.75 -89.25 -88.75 ... 89.25 89.75
  * height            (height) float32 500.0 1e+03 1.5e+03 ... 1.3e+04 5e+04
    release_lon       (release_time) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    release_lat       (release_time) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    release_pressure  (release_time) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    release_npart     (release_time) int32 dask.array<chunksize=(2,), meta=np.ndarray>
  * release_time      (release_time) datetime64[ns] 2018-06-03T03:13:16.50000...
Dimensions without coordinates: numpoint, numspec, nageclass
Data variables: (12/15)
    RELCOM            (numpoint) |S45 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLNG1           (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLNG2           (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLAT1           (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLAT2           (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELZZ1            (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    ...                ...
    RELEND            (numpoint) timedelta64[ns] dask.array<chunksize=(2,), meta=np.ndarray>
    RELPART           (numpoint) int32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELXMASS          (numspec, numpoint) float32 dask.array<chunksize=(1, 2), meta=np.ndarray>
    LAGE              (nageclass) timedelta64[ns] dask.array<chunksize=(1,), meta=np.ndarray>
    ORO               (latitude, longitude) int32 dask.array<chunksize=(360, 720), meta=np.ndarray>
    spec001_mr        (nageclass, release_time, time, height, latitude, longitude) float32 dask.array<chunksize=(1, 1, 3, 27, 360, 720), meta=np.ndarray>
Attributes: (12/37)
    Conventions:            CF-1.6
    title:                  FLEXPART model output
    institution:            NILU
    source:                 Version 10.4 (2019-11-12) model output
    history:                2021-08-04 11:20 +0200  created by macc on n202
    references:             Stohl et al., Atmos. Chem. Phys., 2005, doi:10.51...
    ...                     ...
    ind_source:             2
    ind_receptor:           2
    mquasilag:              0
    nested_output:          0
    surf_only:              0
    linit_cond:             0

In [15]:
ds_test_xrx = xrx.open_dataset_from_netcdf_with_disk_chunks(path, max_chunk_size=1e8)
ds_test_xrx

<xarray.Dataset>
Dimensions:     (time: 240, longitude: 720, latitude: 360, height: 27,
                 numpoint: 2, numspec: 1, nageclass: 1, pointspec: 2)
Coordinates:
  * time        (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:0...
  * longitude   (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude    (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height      (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: numpoint, numspec, nageclass, pointspec
Data variables: (12/15)
    RELCOM      (numpoint) |S45 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLNG1     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLNG2     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLAT1     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLAT2     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELZZ1      (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    ...          ...
    RELEND      (numpoint) timedelta64[ns] dask.array<chunksize=(2,), meta=np.ndarray>
    RELPART     (numpoint) int32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELXMASS    (numspec, numpoint) float32 dask.array<chunksize=(1, 2), meta=np.ndarray>
    LAGE        (nageclass) timedelta64[ns] dask.array<chunksize=(1,), meta=np.ndarray>
    ORO         (latitude, longitude) int32 dask.array<chunksize=(360, 720), meta=np.ndarray>
    spec001_mr  (nageclass, pointspec, time, height, latitude, longitude) float32 dask.array<chunksize=(1, 1, 3, 27, 360, 720), meta=np.ndarray>
Attributes: (12/37)
    Conventions:            CF-1.6
    title:                  FLEXPART model output
    institution:            NILU
    source:                 Version 10.4 (2019-11-12) model output
    history:                2021-08-04 11:20 +0200  created by macc on n202
    references:             Stohl et al., Atmos. Chem. Phys., 2005, doi:10.51...
    ...                     ...
    ind_source:             2
    ind_receptor:           2
    mquasilag:              0
    nested_output:          0
    surf_only:              0
    linit_cond:             0

In [12]:
import netCDF4 # OK quand pas h5netcdf

---

### Bidouilles argmax check FP output

In [1]:
import xarray as xr
from pathlib import Path
import fpout

In [2]:
path = Path('/o3p/patj/SOFT-IO-LI/flexpart10.4/flexpart_v10.4_3d7eebf/src/exercises/soft-io-li/flight_2018_001_1h_05deg/10j_100k_output/grid_time_20180603150000.nc')
path

PosixPath('/o3p/patj/SOFT-IO-LI/flexpart10.4/flexpart_v10.4_3d7eebf/src/exercises/soft-io-li/flight_2018_001_1h_05deg/10j_100k_output/grid_time_20180603150000.nc')

In [5]:
ds = fpout.open_fp_dataset(path, chunks='auto', max_chunk_size=1e8, assign_releases_position_coords=False)
ds

/home/patj/SOFT-IO-LI/src/libs/fpout/fpout/grid_time.py:176: FutureWarning: use open_dataset
  warnings.warn('use open_dataset', FutureWarning)


<xarray.Dataset>
Dimensions:     (time: 240, longitude: 720, latitude: 360, height: 27,
                 numpoint: 2, numspec: 1, nageclass: 1, pointspec: 2)
Coordinates:
  * time        (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:0...
  * longitude   (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude    (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height      (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: numpoint, numspec, nageclass, pointspec
Data variables: (12/15)
    RELCOM      (numpoint) |S45 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLNG1     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLNG2     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLAT1     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELLAT2     (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELZZ1      (numpoint) float32 dask.array<chunksize=(2,), meta=np.ndarray>
    ...          ...
    RELEND      (numpoint) timedelta64[ns] dask.array<chunksize=(2,), meta=np.ndarray>
    RELPART     (numpoint) int32 dask.array<chunksize=(2,), meta=np.ndarray>
    RELXMASS    (numspec, numpoint) float32 dask.array<chunksize=(1, 2), meta=np.ndarray>
    LAGE        (nageclass) timedelta64[ns] dask.array<chunksize=(1,), meta=np.ndarray>
    ORO         (latitude, longitude) int32 dask.array<chunksize=(360, 720), meta=np.ndarray>
    spec001_mr  (nageclass, pointspec, time, height, latitude, longitude) float32 dask.array<chunksize=(1, 1, 3, 27, 360, 720), meta=np.ndarray>
Attributes: (12/37)
    Conventions:            CF-1.6
    title:                  FLEXPART model output
    institution:            NILU
    source:                 Version 10.4 (2019-11-12) model output
    history:                2021-08-04 11:20 +0200  created by macc on n202
    references:             Stohl et al., Atmos. Chem. Phys., 2005, doi:10.51...
    ...                     ...
    ind_source:             2
    ind_receptor:           2
    mquasilag:              0
    nested_output:          0
    surf_only:              0
    linit_cond:             0

In [8]:
da = ds.spec001_mr.squeeze(dim='nageclass').load()
da

<xarray.DataArray 'spec001_mr' (pointspec: 2, time: 240, height: 27,
                                latitude: 360, longitude: 720)>
array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
...
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]]]]], dtype=float32)
Coordinates:
  * time       (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:00:00
  * longitude  (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude   (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [10]:
spec_argmax_lon_lat_ind = da.argmax(dim=['longitude', 'latitude'])
spec_argmax_lon_lat_ind

{'longitude': <xarray.DataArray 'spec001_mr' (pointspec: 2, time: 240, height: 27)>
 array([[[  0,   0,   0, ...,   0,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0],
         ...,
         [317, 315, 281, ..., 265, 191,   6],
         [315, 315, 281, ..., 256, 191,  15],
         [315, 315, 317, ..., 256, 190,  13]],
 
        [[  0,   0,   0, ...,   0,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0],
         ...,
         [220, 220, 220, ...,  75,  49, 709],
         [220, 223, 223, ...,  74,  46, 703],
         [224, 221, 223, ...,  72,  43, 695]]])
 Coordinates:
   * time     (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:00:00
   * height   (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
 Dimensions without coordinates: pointspec,
 'latitude': <xarray.DataArray 'spec001_mr' (pointspec: 2, time: 240, height: 27)>
 array([[[  0,   0,   0, ...,   

In [11]:
da_argmax_lon_lat = da.isel(spec_argmax_lon_lat_ind)
da_argmax_lon_lat # il reste des trucs à 0 

<xarray.DataArray 'spec001_mr' (pointspec: 2, time: 240, height: 27)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.5069321 , 0.5363187 , 0.55358267, ..., 0.1434387 ,
         0.11462416, 0.19211064],
        [0.5812055 , 0.49016124, 0.50742203, ..., 0.19571729,
         0.10173972, 0.21222349],
        [0.49515536, 0.5294034 , 0.6248398 , ..., 0.21748394,
         0.11640222, 0.20801452]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.6335993 , 0.869112  , 0.93641835, ..., 0.5872621 ,
         0.36202154, 0.5176597 ],
        [0.64772284, 0.7571852 , 0.9546391 , ..., 0.54447436,
         0.32363436, 0.47727302],
        [0.6483402 , 0.818442  , 1.0198704 , ..., 0.5696882 ,
         0.3341569 , 0.49877548]]], dtype=float32)
Coordinates:
  * time       (time) datetime64[ns] 2018-06-03T14:00:00 ... 2018-05-24T15:00:00
    longitude  (pointspec, time, height) float32 -179.2 -179.2 ... -157.8 168.2
    latitude   (pointspec, time, height) float32 -89.75 -89.75 ... 41.75 15.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [ ]:
da.where(lon>0)

---

### essais argmax avec un temps précis (moins de valeurs comme ça je comprends mieux)

In [13]:
da2 = da.isel(time=123).squeeze().load()
da2

<xarray.DataArray 'spec001_mr' (pointspec: 2, height: 27, latitude: 360,
                                longitude: 720)>
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
...
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
  * longitude  (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude   (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [14]:
d = da2.argmax(dim=['longitude', 'latitude'])
d

{'longitude': <xarray.DataArray 'spec001_mr' (pointspec: 2, height: 27)>
 array([[262, 259, 265, 262, 267, 265, 265, 262, 256, 249, 223, 236, 255,
         223, 224, 233, 233, 232, 210, 236, 235, 258, 212, 212, 212, 195,
         195],
        [184, 184, 185, 186, 187, 187, 188, 183, 185, 189, 189, 189, 189,
         189, 183, 183, 186, 188, 185, 182, 185, 187, 185,  74,  72,  49,
         185]])
 Coordinates:
     time     datetime64[ns] 2018-05-29T11:00:00
   * height   (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
 Dimensions without coordinates: pointspec,
 'latitude': <xarray.DataArray 'spec001_mr' (pointspec: 2, height: 27)>
 array([[186, 193, 196, 188, 185, 184, 184, 185, 188, 190, 187, 191, 192,
         187, 186, 179, 179, 179, 210, 176, 176, 177, 212, 212, 212, 244,
         218],
        [243, 243, 243, 244, 244, 244, 246, 249, 244, 244, 244, 245, 245,
         244, 245, 245, 245, 236, 241, 213, 247, 246, 247, 239, 241, 237,
         217]])
 Coordinates:
  

In [15]:
result = da2.isel(d) 
result

<xarray.DataArray 'spec001_mr' (pointspec: 2, height: 27)>
array([[0.53831583, 0.8571523 , 0.59932685, 1.0793825 , 1.7914158 ,
        2.82924   , 3.364761  , 2.494957  , 1.8793545 , 1.5009288 ,
        1.6221917 , 2.1440272 , 1.5290186 , 1.7690263 , 1.734479  ,
        1.6077445 , 1.7659742 , 1.9098728 , 1.1626862 , 1.1666512 ,
        0.69012254, 0.66440153, 0.6897735 , 0.69132054, 0.5440857 ,
        0.4202163 , 0.6392664 ],
       [5.0134554 , 5.1326404 , 4.331642  , 3.5424898 , 3.7866454 ,
        3.9101248 , 2.7365959 , 2.2717986 , 1.5703528 , 2.8154423 ,
        3.7627683 , 2.4673305 , 2.4271836 , 1.8815776 , 1.9364258 ,
        1.6094587 , 1.4311502 , 1.7530324 , 1.974864  , 1.7284575 ,
        2.216556  , 2.7353594 , 2.7758737 , 1.6515943 , 1.412432  ,
        1.2204208 , 0.890858  ]], dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
    longitude  (pointspec, height) float32 -48.25 -49.75 ... -154.8 -86.75
    latitude   (pointspec, height) float32 3.25 6.75 8.25 ... 30.75 28.75 18.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [27]:
result.longitude

<xarray.DataArray 'longitude' (pointspec: 2, height: 27)>
array([[ -48.25,  -49.75,  -46.75,  -48.25,  -45.75,  -46.75,  -46.75,
         -48.25,  -51.25,  -54.75,  -67.75,  -61.25,  -51.75,  -67.75,
         -67.25,  -62.75,  -62.75,  -63.25,  -74.25,  -61.25,  -61.75,
         -50.25,  -73.25,  -73.25,  -73.25,  -81.75,  -81.75],
       [ -87.25,  -87.25,  -86.75,  -86.25,  -85.75,  -85.75,  -85.25,
         -87.75,  -86.75,  -84.75,  -84.75,  -84.75,  -84.75,  -84.75,
         -87.75,  -87.75,  -86.25,  -85.25,  -86.75,  -88.25,  -86.75,
         -85.75,  -86.75, -142.25, -143.25, -154.75,  -86.75]],
      dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
    longitude  (pointspec, height) float32 -48.25 -49.75 ... -154.8 -86.75
    latitude   (pointspec, height) float32 3.25 6.75 8.25 ... 30.75 28.75 18.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    long_name:      longitude in degree east
    axis:           Lon
    units:          degrees_east
    standard_name:  grid_longitude
    description:    grid cell centers

In [44]:
result_pointspec = result.assign_coords(pointspec=result.pointspec)
result_pointspec.where(result_pointspec.pointspec==1, drop=True)

<xarray.DataArray 'spec001_mr' (pointspec: 1, height: 27)>
array([[5.0134554, 5.1326404, 4.331642 , 3.5424898, 3.7866454, 3.9101248,
        2.7365959, 2.2717986, 1.5703528, 2.8154423, 3.7627683, 2.4673305,
        2.4271836, 1.8815776, 1.9364258, 1.6094587, 1.4311502, 1.7530324,
        1.974864 , 1.7284575, 2.216556 , 2.7353594, 2.7758737, 1.6515943,
        1.412432 , 1.2204208, 0.890858 ]], dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
    longitude  (pointspec, height) float32 -87.25 -87.25 ... -154.8 -86.75
    latitude   (pointspec, height) float32 31.75 31.75 31.75 ... 28.75 18.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
  * pointspec  (pointspec) int64 1
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [22]:
da2.where(da2>0)

<xarray.DataArray 'spec001_mr' (pointspec: 2, height: 27, latitude: 360,
                                longitude: 720)>
array([[[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
...
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]]], dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
  * longitude  (longitude) float32 -179.2 -178.8 -178.2 ... 179.2 179.8 180.2
  * latitude   (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [ ]:
#### only keep spec001_mr values > 0

In [30]:
da2_where_drop = da2.where(da2>0, drop=True)
da2_where_drop.load()

<xarray.DataArray 'spec001_mr' (pointspec: 2, height: 27, latitude: 122,
                                longitude: 281)>
array([[[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
...
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]]]], dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
  * longitude  (longitude) float32 -160.8 -160.2 -159.8 ... -21.75 -21.25 -20.75
  * latitude   (latitude) float32 -8.25 -7.75 -7.25 -6.75 ... 51.25 51.75 52.25
  * height     (height) float32 500.0 1e+03 1.5e+03 ... 1.25e+04 1.3e+04 5e+04
Dimensions without coordinates: pointspec
Attributes:
    units:        s
    long_name:    AIRTRACER
    decay:        -0.07001485
    weightmolar:  29.0
    ohcconst:     -9e-10
    ohdconst:     -9.9
    vsetaver:     0.0

In [36]:
da2_where_drop.longitude

<xarray.DataArray 'longitude' (longitude: 281)>
array([-160.75, -160.25, -159.75, ...,  -21.75,  -21.25,  -20.75],
      dtype=float32)
Coordinates:
    time       datetime64[ns] 2018-05-29T11:00:00
  * longitude  (longitude) float32 -160.8 -160.2 -159.8 ... -21.75 -21.25 -20.75
Attributes:
    long_name:      longitude in degree east
    axis:           Lon
    units:          degrees_east
    standard_name:  grid_longitude
    description:    grid cell centers

In [47]:
lon_max_argmax = da2_where_drop.longitude.max()
lon_max_argmax

<xarray.DataArray 'longitude' ()>
array(-20.75)
Coordinates:
    time     datetime64[ns] 2018-05-29T11:00:00

In [48]:
lon_min_argmax = da2_where_drop.longitude.min()
lon_min_argmax

<xarray.DataArray 'longitude' ()>
array(-160.75)
Coordinates:
    time     datetime64[ns] 2018-05-29T11:00:00